back/news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path("post/", views.posts, name="posts"),
    path("event/", views.events, name="events"),
    path("event/<int:event_id>/detail", views.event_detail, name="event_detail"),
    path("event/<int:event_id>/edit", views.event_edit, name="event_edit"),
    path("event/create", views.event_create, name="event_create"),
    path(
        "event/<int:event_id>/<str:action>",
        views.event_participate,
        name="event_participate",
    ),
    path("post/<int:post_id>/edit", views.post_edit, name="post_edit"),
    path("post/create", views.post_create, name="post_create"),
    path(
        "post/create/<int:event_id>", views.post_create, name="post_create_with_origin"
    ),
    path("post/<int:post_id>/<str:action>", views.post_like, name="post_like"),
    path("comment/add/<int:post_id>/", views.comment_post, name="comment_post"),
    path(
        "comment/delete/<int:comment_id>/",
        views.delete_comment,
        name="comment_delete",
    ),
    path("shotgun/", views.shotguns, name="shotguns"),
    path("shotgun/<int:shotgun_id>/", views.shotgun_detail, name="shotgun_detail"),
    path(
        "shotgun/<int:shotgun_id>/participate/",
        views.shotgun_participate,
        name="shotgun_participate",
    ),
    path("shotgun/new/", views.new_shotgun, name="new_shotgun"),
    path(
        "shotgun/<int:shotgun_id>/delete/",
        views.delete_shotgun,
        name="delete_shotgun",
    ),
    path(
        "shotgun/<int:shotgun_id>/edit/",
        views.edit_shotgun,
        name="edit_shotgun",
    ),
    path("shotgun/admin/", views.shotguns_admin, name="shotguns_admin"),
    path(
        "shotgun/<int:shotgun_id>/admin/",
        views.shotguns_admin_detail,
        name="shotguns_admin_detail",
    ),
    path(
        "shotgun/admin/fail/<int:participation_id>",
        views.fail_participation,
        name="fail_participation",
    ),
    path(
        "shotgun/admin/unfail/<int:participation_id>",
        views.unfail_participation,
        name="unfail_participation",
    ),
    path(
        "shotgun/<int:shotgun_id>/admin/publish_shotgun_results/",
        views.publish_shotgun_results,
        name="publish_shotgun_results",
    ),
    path(
        "markdown",
        views.markdown,
        name="markdown",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
]

back/social/urls.py
from django.urls import path

from . import views

app_name = "social"
urlpatterns = [
    path("profile/", views.index_users, name="index_users"),
    path("profile/details", views.profile, name="profile"),
    path("profile/<int:user_id>/details", views.profile, name="profile_viewed"),
    path("search", views.search, name="search"),
    path("profile/edit", views.profile_edit, name="profile_edit"),
    path("club/", views.index_clubs, name="club_index"),
    path("club/<int:club_id>/details", views.view_club, name="club_detail"),
    path("club/<int:club_id>/edit", views.club_edit, name="club_edit"),
    path("club/request", views.club_request, name="club_request"),
]

back/upont/urls.py
import django_cas_ng.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django_reverse_js.views import urls_js
from rest_framework import routers

from courses.views import (
    CourseViewSet,
    GroupViewSet,
    ListCourseDepartments,
    ResourceViewSet,
    TimeslotViewSet,
)
from news.views import (
    DeleteCommentView,
    EventViewSet,
    PartnershipViewSet,
    PostCommentView,
    PostCreateView,
    PostCreateViewV2,
    ShotgunCreateView,
    PostDeleteView,
    PostEditView,
    PostReactionView,
    PostViewSet,
    SearchPost,
    ShotgunParticipateView,
    ShotgunView,
)
from pochtron.views import (
    CagnotteURL,
    PochtronBalance,
    PochtronId,
    PochtronTransactions,
    SearchAlcohol,
)

# Replace MediatekViewSet with LocalViewSet
from services.views import (
    BikesViewSet,
    LocalViewSet,
    OrderViewSet,
    RequestFormViewSet,
    ReservationBikeViewSet,
    ReservationMusicRoomViewSet,
    VracViewSet,
)
from social.views import (
    ClubsViewSet,
    CurrentStudentView,
    NotificationTokenView,
    OneClubView,
    OneStudentView,
    ProfilePicUpdate,
    SearchClub,
    SearchRole,
    SearchStudent,
    StudentCanPublishAs,
    StudentMembershipView,
    StudentProfileEdit,
    StudentViewSet,
    validate_student,
)
from the_calendar.views import CalendarData
from trade.views import LastTransactions, add_transaction, credit_account

from . import views

# ---- MAIN URLS ----#

urlpatterns = [
    path("social/", include("social.urls")),
    path("news/", include("news.urls")),
    path("pochtron/", include("pochtron.urls")),
    path("courses/", include("courses.urls")),
    path("the_calendar/", include("the_calendar.urls")),
    path("admin/", admin.site.urls),
    path("tellme/", include("tellme.urls"), name="tellme"),
    path("add_promo/", views.add, name="add_promo"),
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),  # forces redirection of already authenticated users
    path("", include("django.contrib.auth.urls")),
    path("", views.root_redirect),
    path("internal/auth-check/", views.auth_check, name="internal_auth_check"),
    path("cas/login", django_cas_ng.views.LoginView.as_view(), name="cas_ng_login"),
    path("cas/logout", django_cas_ng.views.LogoutView.as_view(), name="cas_ng_logout"),
    path("page_not_created/", views.page_not_created, name="page_not_created"),
    path("privacy", views.privacy, name="privacy"),
    path("contact", views.contact, name="contact"),
]

if settings.DEBUG:  # in debug anyone can access any image
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(path("media/<path:path>", views.media))

# ---- API URLS ----#

router = routers.DefaultRouter()
router.register(
    r"admin-status", views.AdminStatusViewSet, basename="check-admin-status"
)
router.register(r"students", StudentViewSet)
router.register(r"posts", PostViewSet, basename="post")
router.register(r"events", EventViewSet, basename="event")
router.register(r"courses", CourseViewSet, basename="course")
router.register(r"groups", GroupViewSet, basename="group")
router.register(r"timeslots", TimeslotViewSet, basename="timeslot")
router.register(r"resources", ResourceViewSet, basename="resource")
router.register(r"clubs", ClubsViewSet)
router.register(r"services/bikes", BikesViewSet, basename="bikes")
router.register(r"services/orders", OrderViewSet, basename="order")
router.register(r"services/vrac", VracViewSet, basename="vrac")
router.register(r"services/requests", RequestFormViewSet, basename="requests")
router.register(
    r"services/reservations", ReservationBikeViewSet, basename="reservations"
)
router.register(
    r"services/musicroom", ReservationMusicRoomViewSet, basename="musicroom"
)
router.register(r"services/locals", LocalViewSet, basename="local")

router.register(r"partnerships", PartnershipViewSet, basename="partnership")

urlpatterns += [
    path(
        "reverse.js", urls_js, name="reverse_js"
    ),  # for reversing django urls in JavaScript
    path("api/", include(router.urls)),
    path("api/current/", CurrentStudentView.as_view(), name="current_student"),
    path(
        "api/transactions/last/", LastTransactions.as_view(), name="last_transactions"
    ),
    path("api/forms/publish/", StudentCanPublishAs.as_view(), name="publish_comment"),
    path("api/forms/transactions/add/", add_transaction, name="add_transaction"),
    path("api/forms/transactions/credit/", credit_account, name="credit_account"),
    path("api/search/roles/", SearchRole.as_view(), name="search_roles"),
    path("api/search/students/", SearchStudent.as_view(), name="search_students"),
    path("api/search/clubs/", SearchClub.as_view(), name="search_clubs"),
    path("api/search/alcohols/", SearchAlcohol.as_view(), name="search_alcohols"),
    path("api/search/posts/", SearchPost.as_view(), name="search_posts"),
    path("api/id/pochtron/", PochtronId.as_view(), name="pochtron_id"),
    path(
        "api/course_departments/",
        ListCourseDepartments.as_view(),
        name="course_department_list",
    ),
    path("api/calendar_data/", CalendarData.as_view(), name="calendar_data"),
    path("api/get_token/", views.get_token, name="get_token"),
    path("api/get_sso_token/", views.get_sso_token, name="get_sso_token"),
    path("api/shotguns/", ShotgunView.as_view(), name="shotgun"),
    path(
        "api/shotgun/participate/",
        ShotgunParticipateView.as_view(),
        name="shotgun_participate",
    ),
    path(
        "api/notification_token/", NotificationTokenView.as_view(), name="student_token"
    ),
    path("api/post_reaction/", PostReactionView.as_view(), name="post_reaction"),
    path(
        "api/news/post/delete/", PostDeleteView.as_view(), name="api_news_post_delete"
    ),
    path(
        "api/news/comment/delete/",
        DeleteCommentView.as_view(),
        name="api_news_comment_delete",
    ),
    path("api/comment_post/", PostCommentView.as_view(), name="post_comment"),
    path("api/create_post/", PostCreateView.as_view(), name="post_creation"),
    path("api/create_post/v2/", PostCreateViewV2.as_view(), name="post_creation_v2"),
    path("api/create_shotgun/", ShotgunCreateView.as_view(), name="create_shotgun"),
    path("api/edit_post/", PostEditView.as_view(), name="post_edit"),
    path("api/student/", OneStudentView.as_view(), name="student"),
    path("api/membership/", StudentMembershipView.as_view(), name="membership"),
    path("api/club/", OneClubView.as_view(), name="club"),
    path("api/media/<path:path>", views.get_media_path, name="get_media_path"),
    path("api/pochtron/balance/", PochtronBalance.as_view(), name="pochtron_balance"),
    path(
        "api/pochtron/transactions/",
        PochtronTransactions.as_view(),
        name="pochtron_transactions",
    ),
    path("api/pochtron/cagnotte_url/", CagnotteURL.as_view(), name="cagnotte_url"),
    path("api/test/", ProfilePicUpdate.as_view(), name="test"),
    path("api/edit_profile/", StudentProfileEdit.as_view(), name="edit_profile"),
    path("api/validate-student/", validate_student, name="validate_student"),
]

back/social/forms.py
from django import forms

from .models import Club, ClubRequest, Membership, Message, Role, Student

# from django.forms import extras


class EditProfile(forms.ModelForm):
    class Meta:
        model = Student
        fields = (
            "phone_number",
            "department",
            "picture",
            "gender",
            "birthdate",
            "biography",
            "public_key",
        )
        widgets = {
            "phone_number": forms.TextInput(
                attrs={
                    "class": "profil-input",
                    "placeholder": "Numéro de téléphone",
                }
            ),
            "department": forms.Select(attrs={"class": "profil-select"}),
            "picture": forms.FileInput(attrs={"class": "profil-input"}),
            "gender": forms.Select(attrs={"class": "profil-select"}),
            "birthdate": forms.DateInput(
                format="%d/%m/%Y", attrs={"class": "profil-input"}
            ),
            "biography": forms.TextInput(
                attrs={"class": "profil-input", "placeholder": "Biographie"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(EditProfile, self).__init__(*args, **kwargs)
        self.fields["phone_number"].required = False
        self.fields["gender"].choices = [
            ("Homme", "Homme"),
            ("Femme", "Femme"),
            ("Autre", "Autre"),
        ]
        self.fields["phone_number"].placeholder = "False"
        self.fields["birthdate"].required = False


class EditClub(forms.ModelForm):
    class Meta:
        model = Club
        fields = (
            "name",
            "nickname",
            "logo",
            "background_picture",
            "description",
            "active",
            "has_fee",
            "category",
        )
        widgets = {
            "name": forms.TextInput(attrs={"class": "profil-input"}),
            "logo": forms.FileInput(attrs={"class": "profil-input"}),
            "background_picture": forms.FileInput(attrs={"class": "profil-input"}),
            "nickname": forms.TextInput(attrs={"class": "profil-input"}),
            "description": forms.Textarea(attrs={"class": "profil-input"}),
            "category": forms.CheckboxSelectMultiple,
        }

    def __init__(self, *args, **kwargs):
        super(EditClub, self).__init__(*args, **kwargs)
        self.fields["nickname"].required = False
        self.fields["logo"].required = False
        self.fields["background_picture"].required = False
        self.fields["category"].required = False


class AddMember(forms.ModelForm):
    class Meta:
        model = Membership
        fields = ("student", "role", "is_admin")
        widgets = {
            "student": forms.Select(attrs={"class": "profil-select"}),
            "role": forms.Select(attrs={"class": "profil-select"}),
        }

    def __init__(self, *args, **kwargs):
        super(AddMember, self).__init__(*args, **kwargs)


class AddRole(forms.ModelForm):
    class Meta:
        model = Role
        fields = ("name",)
        widgets = {
            "name": forms.TextInput(
                attrs={"class": "profil-input profil-member-create"}
            ),
        }

    def __init__(self, *args, **kwargs):
        super(AddRole, self).__init__(*args, **kwargs)


class ClubRequestForm(forms.ModelForm):
    class Meta:
        model = ClubRequest
        fields = (
            "name",
            "content",
        )
        widgets = {
            "name": forms.TextInput(attrs={"class": "profil-input"}),
            "content": forms.Textarea(attrs={"class": "text-input"}),
        }


class EditMessage(forms.ModelForm):
    class Meta:
        model = Message
        fields = (
            "channel",
            "date",
            "author",
            "club",
            "content",
        )
        widgets = {
            "content": forms.TextInput(attrs={"class": "profil-input"}),
            "date": forms.DateInput(format="%d/%m/%Y", attrs={"class": "profil-input"}),
        }

    def __init__(self, *args, **kwargs):
        super(EditClub, self).__init__(*args, **kwargs)
        self.fields["channel"].required = False
        self.fields["date"].required = False

back/social/templates/social/club_request.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Demande de création d'un club" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="clubs" %}

    <!--Content-->
    <div class="content">

        <!--Header Content-->
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
            </div>
        </div>

        <!--Main Content-->
        <div class="content-main">

            <h3 class="page-title">Demande d'ajout de club</h3>

            <!--Box-->
            <div class="box small-box">

                <!--Form-->
                <form action="" method="POST" class="centered-div">

                    {% csrf_token %}

                    <div class="input-title">Nom du club :</div>
                    {{ ClubRequest.name.errors }}
                    {{ ClubRequest.name }}

                    <div class="input-title mb-2">Décris rapidement le club et motive ta demande :</div>
                    {{ ClubRequest.content.errors }}
                    {{ ClubRequest.content }}

                    <div class="centered-div">
                        <a href="{% url 'social:club_index' %}"><span class="button red-button">Annuler</span></a>
                        <button class="button green-button" type="submit" name="Valider">Valider</button>
                    </div>

                </form><!--End of Form-->

            </div><!--End of Box-->

        </div><!--End of Main Content-->

    </div><!--End of Content-->

</body><!--End of Body-->

</html><!--End of Document-->

back/social/templates/social/profile.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Profil" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="profile" %}

    <!--Content-->
    <div class="content">

        <!--Header Content        -->
        {% include "../social/searchbar.html" with all_student_list=all_student_list %}

        <!--Main Content-->
        <div class="content-main">

            <!--Box-->
            <div class="box profil-box">

                <!--Row-->
                <div class="row">

                    <!--Column-->
                    <div class="col-lg-8">

                        <!--Row-->
                        <div class="row">

                            <!--Column-->
                            <div class="col-lg-5">
                                <div class="profil-image">
                                    <img class="image-centered" src="{% if student.picture %}{{student.picture.url}}{% else %}{% static 'assets/img/user_default.png' %}{% endif %}" alt="">
                                </div>
                            </div>
                            <div class="centered-div col-lg-7">
                                <h5 class="section-title">Mes informations personnelles</h5>
                            </div><!--End of Column-->

                        </div><!--End of Row-->

                        <!--Row-->
                        <div class="row">

                            <!--Column-->
                            <div class="centered-div col-lg-5">
                                <div class="profil-information-box">{% if student.user.first_name %}{{student.user.first_name}}{% else %}---Prénom---{% endif %}</div>
                                <div class="profil-information-box">{% if student.phone_number %}{{student.phone_number}}{% else %}---Tel---{% endif %}</div>
                                <div class="profil-information-box">{% if student.gender %}{{student.gender}}{% else %}------{% endif %}</div>
                                <div class="profil-information-box">{% if student.birthdate %}{{student.birthdate}}{% else %}--mm-dd-yyyy--{% endif %}</div>
                                <div class="profil-information-box">{% if student.biography %}{{student.biography}}{% else %}------{% endif %}</div>
                            </div><!--End of Column-->

                            <!--Column-->
                            <div class="centered-div col-lg-7">
                                <div class="profil-information-box">{% if student.user.last_name %}{{student.user.last_name}}{% else %}---Nom---{% endif %}</div>
                                <div class="profil-information-box">{% if student.department %}{{student.department}}{% else %}-------{% endif %}</div>
                                <div class="profil-information-box">{% if student.origin %}{{student.origin}}{% else %}-------{% endif %}</div>
                            </div><!--End of Column-->

                        </div><!--End of Row-->

                    </div><!--End of Column-->

                    <!--Column-->
                    <div class="col-lg-4">

                        <h5 class="section-title">Mes activités associatives</h5>

                        {% if membership_club_list %}
                            {% for membership in membership_club_list %}
                                <div class="user-card">
                                    <div class="user-image">
                                        <img src="{% if membership.club.logo %}{{membership.club.logo.url}}{% else %}{% static 'assets/img/logo_default.png' %}{% endif %}" alt="">
                                    </div>
                                    <div class="user-information">
                                        <span class="user-name">{{membership.club.name}} {% if membership.club.nickname %}({{membership.club.nickname}}){% endif %}</span>
                                        <span>{{membership.role.name}}</span>
                                        <a href="{% url 'social:club_detail' membership.club.id %}" class="stretched-link"></a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-bold text-center mt-2">Je ne suis pas membre d'un club.</div>
                        {% endif %}
                        <a href="{% url 'social:profile_edit' %}"><button class="button blue-button">Modifier mon profil</button></a>
                        <a href="{% url 'password_change' %}"><button class="button blue-button">Changer mon mot de passe</button></a>
                    </div><!--End of Column-->

                </div><!--End of Row-->

            </div><!--End of Box-->

        </div><!--End of Main Content-->

    </div><!--End of Content-->

</body><!--End of Body-->

</html><!--End of Document-->

back/social/templates/social/searchbar.html
<!--Header Content-->
<div class="content-header">

    <!--Row-->
    <div class="row justify-content-between w-100">

        <!--Column-->
        <div class="col">

            {% if all_student_list%}
                <datalist id="search-choices-student">
                    {% for student in all_student_list %}
                        <option value="{{student.user.first_name}} {{student.user.last_name}} {{student.department}} {{student.promo.nickname}}">
                            {{student.user.first_name}} {{student.user.last_name}} - {{student.department}} - '{{student.promo.nickname}}
                        </option>
                    {% endfor %}
                </datalist>

                <form class="search-input-group">
                    <input name="user" type="text" list="search-choices-student" class="search-input" placeholder="Chercher un élève">
                    <button class="button search-button" type="submit" formaction="{% url 'social:search' %}"><i class="fas fa-search "></i></button>
                </form>
            {% endif %}

            {% if all_clubs_list %}
                <datalist id="search-choices-club">
                    {% for club in all_clubs_list %}
                        <option value="{{club.name}}">{{club.name}} {% if club.nickname %}- {{club.nickname}}{% endif %}</option>
                    {% endfor %}
                    {% for category in all_categories_list %}
                        <option value="{{category.name}}">Catégorie: {{category.name}}</option>
                    {% endfor %}
                </datalist>

                <form class="search-input-group">
                    <input name="club" type="text" list="search-choices-club" class="search-input" placeholder="Chercher un club">
                    <button class="button search-button" type="submit" formaction="{% url 'social:search' %}"><i class="fas fa-search "></i></button>
                </form>
            {% endif %}

        </div><!--End of Column-->

    </div><!--End of Row-->

</div><!--End of Header Content-->

back/social/templates/social/view_club.html
{% load static %}
<!--Markdownify-->
{% load markdownify %}
<!--Header-->
{% include "header.html" with title=club.name %}

<!--Body-->

<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="clubs" %}

    <!--Content-->
    <div class="content">

        <!--Header Content-->
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
            </div>
        </div>

        <!--Main Content-->
        <div class="content-main">

            <!--Club Box-->
            <div class="club-box">

                <div class="club-group-image-container">
                    <img class="club-group-image"
                        src="{% if club.background_picture %}{{club.background_picture.url}}{% else %}{% static 'assets/img/equipe.jpg' %}{% endif %}"
                        alt="">
                </div>

                <!--Row-->
                <div class="row">

                    <!--Column-->
                    <div class="col-lg-4">
                        <div class="club-image">
                            <img class="image-centered"
                                src="{% if club.logo %}{{club.logo.url}}{% else %}{% static 'assets/img/logo_default.png' %}{% endif %}"
                                alt="">
                        </div>
                    </div><!--End of Column-->

                    <!--Column-->
                    <div class="col-lg-8">
                        <div class="club-title">
                            {{club.name}}{% if club.nickname %} -
                                ({{club.nickname}}){% endif %}
                            <a href="{% url 'social:club_index' %}" style="margin-left: auto;"><button
                                class="button green-button">Retour à l'index</button></a>
                        </div>


                    </div><!--End of Column-->

                    <p class="text-thin text-justified mt-2"
                        style="font-size: medium; margin-bottom: 0; padding-bottom:0; ">
                        {%if club.label == "Asso" %} Ceci est une associtation. {%endif%}
                        {%if club.label == "Club" %} Ceci est un club. {%endif%}
                        {%if club.label == "Liste" %} Ceci est une liste.{%endif%}</p>
                    {%if club.label == "Pôle" %} Ceci est un pôle.{%endif%}</p>

                <!--Column-->
                <div class="col-12">

                    <h5 class="section-title text-bold mt-2">Description du club</h5>

                    <p class="text-thin text-justified mt-2" style="font-size: medium; ">
                        {{club.description|markdownify}}</p>

                    <h5 class="section-title text-bold mt-4">Membres du club :</h5>

                    {% if active_members %}
                        <!--End of Row-->
                        <div class="row" style="margin: 1rem -4rem;">

                            {% for membership in active_members %}
                                <!--Column-->
                                <div class="col-xxl-2 col-xl-3 col-lg-4 col-sm-6">
                                    <div class="user-card">
                                        <div class="user-image">
                                            <img src="{% if membership.student.picture %}{{membership.student.picture.url}}{% else %}{% static 'assets/img/user_default.png' %}{% endif %}"
                                                alt="">
                                        </div>
                                        <div class="user-information">
                                            <span class="user-name">{{membership.student.user.first_name}}
                                                {{membership.student.user.last_name}}</span>
                                            <span>{{membership.role}}</span>
                                        </div>
                                        <a href="{% url 'social:profile_viewed' membership.student.user.id %}"
                                            class="stretched-link"></a>
                                    </div>
                                </div><!--End of Column-->
                            {% endfor %}

                        </div><!--End of Row-->
                    {% else %}
                        <p class="text-thin text-center mt-2" style="font-size: medium;">
                            Ce club n'a pas de membres.. à toi de devenir le premier membre du club !
                        </p>
                    {% endif %}


                    <div class="centered-div">
                        {% if is_admin %}
                            <a href="{% url 'social:club_edit' club.id %}">
                                <button class="button blue-button">Modifier les informations du club</button>
                            </a>
                        {% endif %}
                    </div>


                    {% if old_members %}
                        <h5 class="section-title text-bold mt-4">Anciens membres du club :</h5>
                        {% for promo,members in old_members.items %}
                            <h6 class="text-bold mt-4">Promo {{promo}}' :</h6>
                            <div class="row" style="margin: 1rem -4rem;">
                                {% for member in members %}
                                    <!--Column-->
                                    <div class="col-xxl-2 col-xl-3 col-lg-4 col-sm-6">
                                        <div class="user-card">
                                            <div class="user-image">
                                                <img src="{% if member.student.picture %}{{member.student.picture.url}}{% else %}{% static 'assets/img/user_default.png' %}{% endif %}"
                                                    alt="">
                                            </div>
                                            <div class="user-information">
                                                <span class="user-name">{{member.student.user.first_name}}
                                                    {{member.student.user.last_name}}</span>
                                                <span>{{member.role}}</span>
                                            </div>
                                        </div>
                                    </div><!--End of Column-->
                                {% endfor %}
                            </div><!--End of Row-->
                        {% endfor %}
                    {% endif %}

                </div><!--End of Column-->

            </div><!--End of Row-->

        </div><!--End of Club Box-->

    </div><!--End of Main Content-->

</div><!--End of Content-->

</body><!--End of Body-->

</html><!--End of Document-->