back/courses/urls.py
from django.urls import path

from news.views import post_create, post_edit

from . import views

app_name = "courses"

urlpatterns = [
    path("courses/", views.index_courses, name="courses_index"),
    path("course/<int:course_id>/details", views.view_course, name="course_detail"),
    path("update_timeslots/", views.update_timeslots, name="update_timeslots"),
    path("group/<int:group_id>/<str:action>", views.join_group, name="join_group"),
    path("add_course/", views.add, name="add_course"),
    path(
        "course/<int:course_id>/post/create",
        post_create,
        name="course_post_create",
    ),
    path(
        "course/<int:course_id>/post/<int:post_id>/edit",
        post_edit,
        name="course_post_edit",
    ),
]

back/news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path("post/", views.posts, name="posts"),
    path("event/", views.events, name="events"),
    path("event/<int:event_id>/detail", views.event_detail, name="event_detail"),
    path("event/<int:event_id>/edit", views.event_edit, name="event_edit"),
    path("event/create", views.event_create, name="event_create"),
    path(
        "event/<int:event_id>/<str:action>",
        views.event_participate,
        name="event_participate",
    ),
    path("post/<int:post_id>/edit", views.post_edit, name="post_edit"),
    path("post/create", views.post_create, name="post_create"),
    path(
        "post/create/<int:event_id>", views.post_create, name="post_create_with_origin"
    ),
    path("post/<int:post_id>/<str:action>", views.post_like, name="post_like"),
    path("comment/add/<int:post_id>/", views.comment_post, name="comment_post"),
    path(
        "comment/delete/<int:comment_id>/",
        views.delete_comment,
        name="comment_delete",
    ),
    path("shotgun/", views.shotguns, name="shotguns"),
    path("shotgun/<int:shotgun_id>/", views.shotgun_detail, name="shotgun_detail"),
    path(
        "shotgun/<int:shotgun_id>/participate/",
        views.shotgun_participate,
        name="shotgun_participate",
    ),
    path("shotgun/new/", views.new_shotgun, name="new_shotgun"),
    path(
        "shotgun/<int:shotgun_id>/delete/",
        views.delete_shotgun,
        name="delete_shotgun",
    ),
    path(
        "shotgun/<int:shotgun_id>/edit/",
        views.edit_shotgun,
        name="edit_shotgun",
    ),
    path("shotgun/admin/", views.shotguns_admin, name="shotguns_admin"),
    path(
        "shotgun/<int:shotgun_id>/admin/",
        views.shotguns_admin_detail,
        name="shotguns_admin_detail",
    ),
    path(
        "shotgun/admin/fail/<int:participation_id>",
        views.fail_participation,
        name="fail_participation",
    ),
    path(
        "shotgun/admin/unfail/<int:participation_id>",
        views.unfail_participation,
        name="unfail_participation",
    ),
    path(
        "shotgun/<int:shotgun_id>/admin/publish_shotgun_results/",
        views.publish_shotgun_results,
        name="publish_shotgun_results",
    ),
    path(
        "markdown",
        views.markdown,
        name="markdown",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
]

back/upont/urls.py
import django_cas_ng.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django_reverse_js.views import urls_js
from rest_framework import routers

from courses.views import (
    CourseViewSet,
    GroupViewSet,
    ListCourseDepartments,
    ResourceViewSet,
    TimeslotViewSet,
)
from news.views import (
    DeleteCommentView,
    EventViewSet,
    PartnershipViewSet,
    PostCommentView,
    PostCreateView,
    PostCreateViewV2,
    ShotgunCreateView,
    PostDeleteView,
    PostEditView,
    PostReactionView,
    PostViewSet,
    SearchPost,
    ShotgunParticipateView,
    ShotgunView,
)
from pochtron.views import (
    CagnotteURL,
    PochtronBalance,
    PochtronId,
    PochtronTransactions,
    SearchAlcohol,
)

# Replace MediatekViewSet with LocalViewSet
from services.views import (
    BikesViewSet,
    LocalViewSet,
    OrderViewSet,
    RequestFormViewSet,
    ReservationBikeViewSet,
    ReservationMusicRoomViewSet,
    VracViewSet,
)
from social.views import (
    ClubsViewSet,
    CurrentStudentView,
    NotificationTokenView,
    OneClubView,
    OneStudentView,
    ProfilePicUpdate,
    SearchClub,
    SearchRole,
    SearchStudent,
    StudentCanPublishAs,
    StudentMembershipView,
    StudentProfileEdit,
    StudentViewSet,
    validate_student,
)
from the_calendar.views import CalendarData
from trade.views import LastTransactions, add_transaction, credit_account

from . import views

# ---- MAIN URLS ----#

urlpatterns = [
    path("social/", include("social.urls")),
    path("news/", include("news.urls")),
    path("pochtron/", include("pochtron.urls")),
    path("courses/", include("courses.urls")),
    path("the_calendar/", include("the_calendar.urls")),
    path("admin/", admin.site.urls),
    path("tellme/", include("tellme.urls"), name="tellme"),
    path("add_promo/", views.add, name="add_promo"),
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),  # forces redirection of already authenticated users
    path("", include("django.contrib.auth.urls")),
    path("", views.root_redirect),
    path("internal/auth-check/", views.auth_check, name="internal_auth_check"),
    path("cas/login", django_cas_ng.views.LoginView.as_view(), name="cas_ng_login"),
    path("cas/logout", django_cas_ng.views.LogoutView.as_view(), name="cas_ng_logout"),
    path("page_not_created/", views.page_not_created, name="page_not_created"),
    path("privacy", views.privacy, name="privacy"),
    path("contact", views.contact, name="contact"),
]

if settings.DEBUG:  # in debug anyone can access any image
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(path("media/<path:path>", views.media))

# ---- API URLS ----#

router = routers.DefaultRouter()
router.register(
    r"admin-status", views.AdminStatusViewSet, basename="check-admin-status"
)
router.register(r"students", StudentViewSet)
router.register(r"posts", PostViewSet, basename="post")
router.register(r"events", EventViewSet, basename="event")
router.register(r"courses", CourseViewSet, basename="course")
router.register(r"groups", GroupViewSet, basename="group")
router.register(r"timeslots", TimeslotViewSet, basename="timeslot")
router.register(r"resources", ResourceViewSet, basename="resource")
router.register(r"clubs", ClubsViewSet)
router.register(r"services/bikes", BikesViewSet, basename="bikes")
router.register(r"services/orders", OrderViewSet, basename="order")
router.register(r"services/vrac", VracViewSet, basename="vrac")
router.register(r"services/requests", RequestFormViewSet, basename="requests")
router.register(
    r"services/reservations", ReservationBikeViewSet, basename="reservations"
)
router.register(
    r"services/musicroom", ReservationMusicRoomViewSet, basename="musicroom"
)
router.register(r"services/locals", LocalViewSet, basename="local")

router.register(r"partnerships", PartnershipViewSet, basename="partnership")

urlpatterns += [
    path(
        "reverse.js", urls_js, name="reverse_js"
    ),  # for reversing django urls in JavaScript
    path("api/", include(router.urls)),
    path("api/current/", CurrentStudentView.as_view(), name="current_student"),
    path(
        "api/transactions/last/", LastTransactions.as_view(), name="last_transactions"
    ),
    path("api/forms/publish/", StudentCanPublishAs.as_view(), name="publish_comment"),
    path("api/forms/transactions/add/", add_transaction, name="add_transaction"),
    path("api/forms/transactions/credit/", credit_account, name="credit_account"),
    path("api/search/roles/", SearchRole.as_view(), name="search_roles"),
    path("api/search/students/", SearchStudent.as_view(), name="search_students"),
    path("api/search/clubs/", SearchClub.as_view(), name="search_clubs"),
    path("api/search/alcohols/", SearchAlcohol.as_view(), name="search_alcohols"),
    path("api/search/posts/", SearchPost.as_view(), name="search_posts"),
    path("api/id/pochtron/", PochtronId.as_view(), name="pochtron_id"),
    path(
        "api/course_departments/",
        ListCourseDepartments.as_view(),
        name="course_department_list",
    ),
    path("api/calendar_data/", CalendarData.as_view(), name="calendar_data"),
    path("api/get_token/", views.get_token, name="get_token"),
    path("api/get_sso_token/", views.get_sso_token, name="get_sso_token"),
    path("api/shotguns/", ShotgunView.as_view(), name="shotgun"),
    path(
        "api/shotgun/participate/",
        ShotgunParticipateView.as_view(),
        name="shotgun_participate",
    ),
    path(
        "api/notification_token/", NotificationTokenView.as_view(), name="student_token"
    ),
    path("api/post_reaction/", PostReactionView.as_view(), name="post_reaction"),
    path(
        "api/news/post/delete/", PostDeleteView.as_view(), name="api_news_post_delete"
    ),
    path(
        "api/news/comment/delete/",
        DeleteCommentView.as_view(),
        name="api_news_comment_delete",
    ),
    path("api/comment_post/", PostCommentView.as_view(), name="post_comment"),
    path("api/create_post/", PostCreateView.as_view(), name="post_creation"),
    path("api/create_post/v2/", PostCreateViewV2.as_view(), name="post_creation_v2"),
    path("api/create_shotgun/", ShotgunCreateView.as_view(), name="create_shotgun"),
    path("api/edit_post/", PostEditView.as_view(), name="post_edit"),
    path("api/student/", OneStudentView.as_view(), name="student"),
    path("api/membership/", StudentMembershipView.as_view(), name="membership"),
    path("api/club/", OneClubView.as_view(), name="club"),
    path("api/media/<path:path>", views.get_media_path, name="get_media_path"),
    path("api/pochtron/balance/", PochtronBalance.as_view(), name="pochtron_balance"),
    path(
        "api/pochtron/transactions/",
        PochtronTransactions.as_view(),
        name="pochtron_transactions",
    ),
    path("api/pochtron/cagnotte_url/", CagnotteURL.as_view(), name="cagnotte_url"),
    path("api/test/", ProfilePicUpdate.as_view(), name="test"),
    path("api/edit_profile/", StudentProfileEdit.as_view(), name="edit_profile"),
    path("api/validate-student/", validate_student, name="validate_student"),
]

back/courses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from news.models import Post
from social.models import Student


class Teacher(models.Model):
    name = models.CharField(max_length=100, default="Professeur anonyme")

    def __str__(self):
        return self.name


class CourseDepartment(models.TextChoices):
    IMI = "IMI", _("Ingénierie mathématique et informatique")
    GCC = "GCC", _("Génie civil et construction")
    GMM = "GMM", _("Génie mécanique et matériaux")
    SEGF = "SEGF", _("Sciences économiques, gestion, finance")
    VET = "VET", _("Ville, environnement, transport")
    GI = "GI", _("Génie industriel")
    A1 = "1A", _("Première année")
    DE = "DE", _("Direction de l'enseignement")
    DLC = "DLC", _("Département langues et culture")
    SHS = "SHS", _("Sciences humaines et sociales")
    PAPDD = "PAPDD", _("Politique et action publique pour le développement durable")
    DS = "D.SCHOOL", _("d.school")
    AHE = "AHE", _("Autres hors école")


class Course(models.Model):
    name = models.CharField(max_length=100, default="Cours sans nom")
    acronym = models.CharField(max_length=100, default="ABC")
    department = models.CharField(
        max_length=8, choices=CourseDepartment.choices, default=CourseDepartment.AHE
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    description = models.TextField()
    old_courses = models.ManyToManyField(
        "self",
        through="CourseUpdate",
        symmetrical=False,
        related_name="new_courses",
        blank=True,
    )
    posts = models.ManyToManyField(
        Post,
        related_name="course",
        blank=True,
    )

    def __str__(self):
        return self.name


class CourseUpdate(models.Model):
    date = models.DateTimeField()
    old_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="old")
    new_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="new")

    def __str__(self):
        return self.old_course.name + " : " + self.new_course.name


class Group(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="groups")
    teacher = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, related_name="groups"
    )
    number = models.IntegerField(blank=True, null=True)
    students = models.ManyToManyField(
        Student,
        through="Enrolment",
        related_name="course",
        blank=True,
    )

    def __str__(self):
        if self.number is None:
            return "{} : {}".format(self.course.name, self.teacher.name)
        else:
            return "{} ({}) : {}".format(
                self.course.name, self.number, self.teacher.name
            )


class Enrolment(models.Model):
    is_old = models.BooleanField(default=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return self.group.course.name + " : " + self.student.user.username


class Timeslot(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    course_groups = models.ManyToManyField(Group, related_name="timeslot", blank=True)
    place = models.CharField(max_length=50, blank=True)

    def get_course_name(self):
        """
        Return the name of the corresponding course
        Return None if it is attached to no course
        """
        if self.course_groups.exists():
            course_name = self.course_groups.first().course.name
        else:
            course_name = None

        return course_name


class Resource(models.Model):
    name = models.CharField(max_length=50, default="Ressource")
    author = models.ForeignKey(
        "social.Student", verbose_name="author", on_delete=models.SET_NULL, null=True
    )
    date = models.DateTimeField()
    file = models.FileField("Fichier", upload_to="ressources", null=True, blank=True)
    post = models.ForeignKey(
        "news.Post",
        verbose_name="post",
        on_delete=models.CASCADE,
        null=True,
        related_name="resource",
    )

back/trade/models.py
from django.db import models


class Price(models.Model):  # changing prices are handled with a Price model
    good = models.ForeignKey("trade.Good", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField()
    price = models.IntegerField()  # in 100th of euros


class Good(models.Model):
    name = models.CharField(max_length=50)
    club = models.ForeignKey("social.Club", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def price_object(self):
        return Price.objects.filter(good=self).order_by("-date")[0]

    def price(self):
        return self.price_object().price

    def price_at_date(self, date):
        return (
            Price.objects.filter(good=self, date__lte=date).order_by("-date")[0].price
        )


class Transaction(models.Model):
    good = models.ForeignKey("Good", on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    student = models.ForeignKey("social.Student", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField()

    def __str__(self):
        string_to_return = self.good.name + " : "
        if self.student is not None:
            string_to_return += self.student.user.username
        return string_to_return

    def balance_change_for_student(self):
        return -(self.quantity * self.good.price_at_date(self.date))

    def balance_change_for_club(self):
        return self.quantity * self.good.price_at_date(self.date)


class TradeAdmin(models.Model):
    student = models.ForeignKey("social.Student", on_delete=models.CASCADE)
    club = models.ForeignKey("social.Club", on_delete=models.CASCADE)
    manage_admins = models.BooleanField(default=False)
    manage_goods = models.BooleanField(default=False)
    manage_transactions = models.BooleanField(default=False)
    manage_credits = models.BooleanField(default=False)

    class Meta:
        unique_together = ("student", "club")

    def __str__(self):
        return "TradeAdmin: {} for {}".format(
            self.student.user.username, self.club.name
        )

back/news/templates/news/post_edit.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Modifier la publication" %}

<!--Body-->

<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="news" %}

    <!--Content-->
    <div class="content">

        <!--Main Content-->
        <div class="content-main">

            <h3 class="page-title">{% if Edit %}Éditer{% else %}Créer{% endif %} un post</h3>

            <!--News Card-->
            <div class="news-card">
                <form action="
                    {% if Edit %}
                        {%if course_id == None%}
                            {% url 'news:post_edit' post.id %}
                        {%else%}
                            {%url 'courses:course_post_edit' post_id=post.id course_id=course_id%}
                        {%endif%}
                    {% else%}
                        {%if course_id == None%}
                            {% url 'news:post_create'%}
                        {%else%}
                            {%url 'courses:course_post_create' course_id=course_id%}
                        {%endif%}
                    {% endif %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="news-card-content">
                        <div class="centered-div">
                            {{EditPost.club.errors}}
                            {% if EditPost.club|length > 1 %}
                                <div class="input-title">Publier en tant que :</div>
                                {{EditPost.club}}
                            {% endif %}

                            {{EditPost.event.errors}}
                            <div class="input-title">Est-ce que ce post est associé à un évènement ?</div>
                            {{EditPost.event}}

                            {{EditPost.title.errors}}
                            <div class="input-title">Titre :</div>
                            {{EditPost.title}}<br>

                            {{EditPost.content.errors}}
                            <div class="input-title">Description :</div>
                            {{EditPost.content}}<br><br>
                            <p>Tu peux écrire en markdown, clique <a href="{% url 'news:markdown' %}"
                                target="_blank">sur ce lien</a> pour en savoir plus.</p>

                            {%if course_id != None%}
                                {{EditPost.resource_file.errors}}
                                <div class="input-title">Ajouter/modifier une ressource:</div>
                                {{EditPost.resource_file}}
                            {%endif%}

                            {{EditPost.illustration.errors}}
                            <div class="input-title">Ajouter/modifier une image :</div>
                            {{EditPost.illustration}}<br>

                            {{EditPost.video.errors}}
                            <div class="input-title">Ajouter/modifier une vidéo :</div>
                            {{EditPost.video}}<br>

                        </div>
                    </div>
                    {%if post.illustration%}
                        <div class="news-card-images">
                            <!--All-Images-Linked-With-The-Post-->
                            <div class="news-card-carousel">
                                <div class="carousel-cell">
                                    <img class="news-card_image_sized" src="{{post.illustration.url}}" alt="">
                                </div>
                            </div>
                        </div>
                    {%endif%}
                    <div class="centered-div">
                        <button type="button" class="button red-button" onclick="history.back()">Annuler</button>
                        <input class="button green-button" type="submit" name="Valider" value="Valider">
                        {% if Edit %}
                            <input class="button red-button" type="submit" name="Supprimer" value="Supprimer le post">
                        {% endif %}
                    </div>
                </form>
            </div><!--End of News Card-->

        </div><!--End of Main Content-->

    </div><!--End of Content-->

</body><!--End of Body-->

</html><!--End of Document-->

back/news/templates/news/shotguns_admin_detail.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Gestion du shotgun" %}

<!--Body-->

<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="news" %}

    <!--Content-->
    <div class="content">

        <!--Header Content-->
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
            </div>
        </div>

        <!--Main Content-->
        <div class="content-main">

            <!--Row-->
            <div class="row">

                <!--Column-->
                <div class="col-clublg-6">

                    <h3 class="page-title mt-2">Édition du shotgun</h3>

                    <!--Box-->
                    <div class="box small-box">
                        <h5 class="section-title">Information sur ce shotgun : {{shotgun.title}}</h5>
                        <ul class="">
                            <li>
                                <div class="text-bold mt-2">Organisateur : <strong
                                    class="text-thin">{{shotgun.club.name}}</strong></div>
                            </li>
                            {%if shotgun.is_started%}
                                <li>
                                    <div class="text-bold mt-2">Ce shotgun a commencé !</div>
                                </li>
                            {%elif not shotgun.is_ended%}
                                <li>
                                    <div class="text-bold mt-2">Début du shotgun : <strong
                                        class="text-thin">{{shotgun.starting_date}}</strong></div>
                                </li>
                            {%endif%}
                            <li>
                                <div class="text-bold mt-2">Fin du shotgun : <strong
                                    class="text-thin">{{shotgun.ending_date}}</strong></div>
                            </li>
                            <li>
                                <div class="text-bold mt-2">Motivation : <strong class="text-thin">
                                    {%if shotgun.requires_motivation%}Requise.{%else%}Non.{%endif%}
                                </strong></div>
                            </li>
                            <li>
                                <div class="text-bold mt-2">Nombre de places : <strong
                                    class="text-thin">{{shotgun.size}}</strong></div>
                            </li>
                            <li>
                                <div class="text-bold mt-2">Description : <strong
                                    class="text-thin">{{shotgun.content}}</strong></div>
                            </li>
                            <li>
                                <div class="text-bold mt-2">Message en cas de succès : <strong
                                    class="text-thin">{{shotgun.success_message}}</strong></div>
                            </li>
                            <li>
                                <div class="text-bold mt-2">Message en cas d'échec : <strong
                                    class="text-thin">{{shotgun.failure_message}}</strong></div>
                            </li>
                        </ul>

                        <div class="centered-div">
                            <a href="{% url 'news:edit_shotgun' shotgun.id %}"><button
                                class="button green-button">Éditer</button></a>
                            <a href="{% url 'news:delete_shotgun' shotgun.id %}"><button
                                class="button red-button">Supprimer</button></a>
                            <a href="{% url 'news:shotgun_detail' shotgun.id %}"><button
                                class="button blue-button">Retour</button></a>
                        </div>
                    </div><!--End of Box-->

                </div><!--End of Column-->

                <!--Column-->
                <div class="col-clublg-6">

                    <h3 class="page-title mt-2">Participations</h3>

                    {% if not shotgun.is_ended%}
                        <div class="box small-box">
                            <h5 class="section-title">
                                <strong class="text-bold">Le shotgun n'est pas encore terminé.</strong>
                            </h5>
                        </div>
                    {% else %}
                        <!--Box-->
                        <div class="box small-box">
                            {% if shotgun.motivations_review_finished %}
                                <h5 class="section-title">
                                    <strong class="text-bold">Les résultats ont été publiés !</strong>
                                    <br>
                                    <strong class="text-bold">Ci-dessous les participations acceptées !</strong>
                                </h5>
                            {% else %}
                                <h5 class="section-title">
                                    <strong class="text-bold">Les participations sont anonymes et s'affichent par ordre de
                                        shotgun.</strong>
                                    <br>
                                    <strong class="text-thin">Les {{shotgun.size}} premières participations non recalées seront
                                        acceptées.</strong>
                                </h5>
                                <div class="centered-div">
                                    <a href="{% url 'news:publish_shotgun_results' shotgun.id %}"><button
                                        class="button red-button">Publier les résultats</button></a>
                                </div>
                            {% endif %}
                        </div><!--End of Box-->
                    {% endif %}

                    {% if shotgun.requires_motivation and not shotgun.motivations_review_finished %}
                        {% for participation in shotgun.participations %}
                            <!--Box-->
                            <div class="box small-box">

                                <h5 class="section-title">
                                    Participation n°{{participation.rank}} :
                                    {% if participation.failed_motivation %}
                                        <strong class="text-bold text-green">Participation recalée !</strong>
                                    {% endif %}
                                </h5>

                                <div class="centered-div mt-3">
                                    <div class="information-box">{{participation.motivation}}</div>
                                    {% if participation.failed_motivation %}
                                        <a href="{% url 'news:unfail_participation' participation.id %}"><button
                                            class="button red-button">Annuler</button></a>
                                    {% else %}
                                        <a href="{% url 'news:fail_participation' participation.id %}"><button
                                            class="button red-button">Recaler</button></a>
                                    {% endif %}
                                </div>

                            </div><!--End of Box-->
                        {% empty %}
                            <!--Box-->
                            <div class="box small-box">
                                <h5 class="section-title">Pas de participation pour l'instant.</h5>
                            </div><!--End of Box-->
                        {% endfor %}
                    {% else %}
                        {% for participation in shotgun.accepted_participations %}
                            <!--Box-->
                            <div class="box small-box">
                                <h5 class="section-title text-bold">{{participation.participant.user.first_name}}
                                    {{participation.participant.user.last_name}}</h5>
                                {% if shotgun.requires_motivation %}
                                    <div class="centered-div mt-3">
                                        <div class="information-box">{{participation.motivation}}</div>
                                    </div>
                                {% endif %}
                            </div><!--End of Box-->
                        {% empty %}
                            <!--Box-->
                            <div class="box small-box">
                                <h5 class="section-title">Personne n'a été accepté.</h5>
                            </div><!--End of Box-->
                        {% endfor %}
                    {% endif %}

                    <h3 class="page-title mt-2">Liste d'attente</h3>
                    {% for participation in shotgun.denied %}
                        <!--Box-->
                        <div class="box small-box">
                            <h5 class="section-title text-bold">{{participation.participant.user.first_name}}
                                {{participation.participant.user.last_name}}</h5>
                        </div><!--End of Box-->
                    {% empty %}
                        <!--Box-->
                        <div class="box small-box">
                            <h5 class="section-title">Personne n'est en ligne d'attente.</h5>
                        </div><!--End of Box-->
                    {% endfor %}
                </div><!--End of Column-->

            </div><!--End of Row-->

        </div><!--End of Main Content-->

    </div><!--End of Content-->

</body><!--End of Body-->

</html><!--End of Document-->