back/news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path("post/", views.posts, name="posts"),
    path("event/", views.events, name="events"),
    path("event/<int:event_id>/detail", views.event_detail, name="event_detail"),
    path("event/<int:event_id>/edit", views.event_edit, name="event_edit"),
    path("event/create", views.event_create, name="event_create"),
    path(
        "event/<int:event_id>/<str:action>",
        views.event_participate,
        name="event_participate",
    ),
    path("post/<int:post_id>/edit", views.post_edit, name="post_edit"),
    path("post/create", views.post_create, name="post_create"),
    path(
        "post/create/<int:event_id>", views.post_create, name="post_create_with_origin"
    ),
    path("post/<int:post_id>/<str:action>", views.post_like, name="post_like"),
    path("comment/add/<int:post_id>/", views.comment_post, name="comment_post"),
    path(
        "comment/delete/<int:comment_id>/",
        views.delete_comment,
        name="comment_delete",
    ),
    path("shotgun/", views.shotguns, name="shotguns"),
    path("shotgun/<int:shotgun_id>/", views.shotgun_detail, name="shotgun_detail"),
    path(
        "shotgun/<int:shotgun_id>/participate/",
        views.shotgun_participate,
        name="shotgun_participate",
    ),
    path("shotgun/new/", views.new_shotgun, name="new_shotgun"),
    path(
        "shotgun/<int:shotgun_id>/delete/",
        views.delete_shotgun,
        name="delete_shotgun",
    ),
    path(
        "shotgun/<int:shotgun_id>/edit/",
        views.edit_shotgun,
        name="edit_shotgun",
    ),
    path("shotgun/admin/", views.shotguns_admin, name="shotguns_admin"),
    path(
        "shotgun/<int:shotgun_id>/admin/",
        views.shotguns_admin_detail,
        name="shotguns_admin_detail",
    ),
    path(
        "shotgun/admin/fail/<int:participation_id>",
        views.fail_participation,
        name="fail_participation",
    ),
    path(
        "shotgun/admin/unfail/<int:participation_id>",
        views.unfail_participation,
        name="unfail_participation",
    ),
    path(
        "shotgun/<int:shotgun_id>/admin/publish_shotgun_results/",
        views.publish_shotgun_results,
        name="publish_shotgun_results",
    ),
    path(
        "markdown",
        views.markdown,
        name="markdown",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
]

back/pochtron/urls.py
from django.urls import include, path

from . import views

app_name = "pochtron"

urlpatterns = [
    path("", include("trade.urls"), name="trade"),
    path("", views.home, name="home"),
    path("stats/", views.user_stats, name="user_stats"),
    path("admin/", views.admin_home_page, name="admin"),
    path("admin/accounts/", views.manage_accounts, name="manage_accounts"),
    path("admin/shop/", views.shop, name="shop"),
    path("admin/conso/create/", views.conso_create, name="conso_create"),
    path("admin/conso/edit/<int:conso_id>/", views.conso_edit, name="conso_edit"),
    path("admin/manage_admins/", views.manage_admins, name="manage_admins"),
    path(
        "admin/manage_admins/edit/<int:admin_id>", views.admin_edit, name="admin_edit"
    ),
    path("admin/manage_admins/create", views.admin_create, name="admin_create"),
]

back/upont/urls.py
import django_cas_ng.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django_reverse_js.views import urls_js
from rest_framework import routers

from courses.views import (
    CourseViewSet,
    GroupViewSet,
    ListCourseDepartments,
    ResourceViewSet,
    TimeslotViewSet,
)
from news.views import (
    DeleteCommentView,
    EventViewSet,
    PartnershipViewSet,
    PostCommentView,
    PostCreateView,
    PostCreateViewV2,
    ShotgunCreateView,
    PostDeleteView,
    PostEditView,
    PostReactionView,
    PostViewSet,
    SearchPost,
    ShotgunParticipateView,
    ShotgunView,
)
from pochtron.views import (
    CagnotteURL,
    PochtronBalance,
    PochtronId,
    PochtronTransactions,
    SearchAlcohol,
)

# Replace MediatekViewSet with LocalViewSet
from services.views import (
    BikesViewSet,
    LocalViewSet,
    OrderViewSet,
    RequestFormViewSet,
    ReservationBikeViewSet,
    ReservationMusicRoomViewSet,
    VracViewSet,
)
from social.views import (
    ClubsViewSet,
    CurrentStudentView,
    NotificationTokenView,
    OneClubView,
    OneStudentView,
    ProfilePicUpdate,
    SearchClub,
    SearchRole,
    SearchStudent,
    StudentCanPublishAs,
    StudentMembershipView,
    StudentProfileEdit,
    StudentViewSet,
    validate_student,
)
from the_calendar.views import CalendarData
from trade.views import LastTransactions, add_transaction, credit_account

from . import views

# ---- MAIN URLS ----#

urlpatterns = [
    path("social/", include("social.urls")),
    path("news/", include("news.urls")),
    path("pochtron/", include("pochtron.urls")),
    path("courses/", include("courses.urls")),
    path("the_calendar/", include("the_calendar.urls")),
    path("admin/", admin.site.urls),
    path("tellme/", include("tellme.urls"), name="tellme"),
    path("add_promo/", views.add, name="add_promo"),
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),  # forces redirection of already authenticated users
    path("", include("django.contrib.auth.urls")),
    path("", views.root_redirect),
    path("internal/auth-check/", views.auth_check, name="internal_auth_check"),
    path("cas/login", django_cas_ng.views.LoginView.as_view(), name="cas_ng_login"),
    path("cas/logout", django_cas_ng.views.LogoutView.as_view(), name="cas_ng_logout"),
    path("page_not_created/", views.page_not_created, name="page_not_created"),
    path("privacy", views.privacy, name="privacy"),
    path("contact", views.contact, name="contact"),
]

if settings.DEBUG:  # in debug anyone can access any image
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(path("media/<path:path>", views.media))

# ---- API URLS ----#

router = routers.DefaultRouter()
router.register(
    r"admin-status", views.AdminStatusViewSet, basename="check-admin-status"
)
router.register(r"students", StudentViewSet)
router.register(r"posts", PostViewSet, basename="post")
router.register(r"events", EventViewSet, basename="event")
router.register(r"courses", CourseViewSet, basename="course")
router.register(r"groups", GroupViewSet, basename="group")
router.register(r"timeslots", TimeslotViewSet, basename="timeslot")
router.register(r"resources", ResourceViewSet, basename="resource")
router.register(r"clubs", ClubsViewSet)
router.register(r"services/bikes", BikesViewSet, basename="bikes")
router.register(r"services/orders", OrderViewSet, basename="order")
router.register(r"services/vrac", VracViewSet, basename="vrac")
router.register(r"services/requests", RequestFormViewSet, basename="requests")
router.register(
    r"services/reservations", ReservationBikeViewSet, basename="reservations"
)
router.register(
    r"services/musicroom", ReservationMusicRoomViewSet, basename="musicroom"
)
router.register(r"services/locals", LocalViewSet, basename="local")

router.register(r"partnerships", PartnershipViewSet, basename="partnership")

urlpatterns += [
    path(
        "reverse.js", urls_js, name="reverse_js"
    ),  # for reversing django urls in JavaScript
    path("api/", include(router.urls)),
    path("api/current/", CurrentStudentView.as_view(), name="current_student"),
    path(
        "api/transactions/last/", LastTransactions.as_view(), name="last_transactions"
    ),
    path("api/forms/publish/", StudentCanPublishAs.as_view(), name="publish_comment"),
    path("api/forms/transactions/add/", add_transaction, name="add_transaction"),
    path("api/forms/transactions/credit/", credit_account, name="credit_account"),
    path("api/search/roles/", SearchRole.as_view(), name="search_roles"),
    path("api/search/students/", SearchStudent.as_view(), name="search_students"),
    path("api/search/clubs/", SearchClub.as_view(), name="search_clubs"),
    path("api/search/alcohols/", SearchAlcohol.as_view(), name="search_alcohols"),
    path("api/search/posts/", SearchPost.as_view(), name="search_posts"),
    path("api/id/pochtron/", PochtronId.as_view(), name="pochtron_id"),
    path(
        "api/course_departments/",
        ListCourseDepartments.as_view(),
        name="course_department_list",
    ),
    path("api/calendar_data/", CalendarData.as_view(), name="calendar_data"),
    path("api/get_token/", views.get_token, name="get_token"),
    path("api/get_sso_token/", views.get_sso_token, name="get_sso_token"),
    path("api/shotguns/", ShotgunView.as_view(), name="shotgun"),
    path(
        "api/shotgun/participate/",
        ShotgunParticipateView.as_view(),
        name="shotgun_participate",
    ),
    path(
        "api/notification_token/", NotificationTokenView.as_view(), name="student_token"
    ),
    path("api/post_reaction/", PostReactionView.as_view(), name="post_reaction"),
    path(
        "api/news/post/delete/", PostDeleteView.as_view(), name="api_news_post_delete"
    ),
    path(
        "api/news/comment/delete/",
        DeleteCommentView.as_view(),
        name="api_news_comment_delete",
    ),
    path("api/comment_post/", PostCommentView.as_view(), name="post_comment"),
    path("api/create_post/", PostCreateView.as_view(), name="post_creation"),
    path("api/create_post/v2/", PostCreateViewV2.as_view(), name="post_creation_v2"),
    path("api/create_shotgun/", ShotgunCreateView.as_view(), name="create_shotgun"),
    path("api/edit_post/", PostEditView.as_view(), name="post_edit"),
    path("api/student/", OneStudentView.as_view(), name="student"),
    path("api/membership/", StudentMembershipView.as_view(), name="membership"),
    path("api/club/", OneClubView.as_view(), name="club"),
    path("api/media/<path:path>", views.get_media_path, name="get_media_path"),
    path("api/pochtron/balance/", PochtronBalance.as_view(), name="pochtron_balance"),
    path(
        "api/pochtron/transactions/",
        PochtronTransactions.as_view(),
        name="pochtron_transactions",
    ),
    path("api/pochtron/cagnotte_url/", CagnotteURL.as_view(), name="cagnotte_url"),
    path("api/test/", ProfilePicUpdate.as_view(), name="test"),
    path("api/edit_profile/", StudentProfileEdit.as_view(), name="edit_profile"),
    path("api/validate-student/", validate_student, name="validate_student"),
]

back/pochtron/models.py
from django.db import models

from trade.models import Good


class Alcohol(Good):
    degree = models.IntegerField("degree (permil)")
    volume = models.IntegerField("volume (mL)")

    def __str__(self):
        return self.name


class ConfigURL(models.Model):
    url = models.CharField(max_length=200)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

back/trade/models.py
from django.db import models


class Price(models.Model):  # changing prices are handled with a Price model
    good = models.ForeignKey("trade.Good", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField()
    price = models.IntegerField()  # in 100th of euros


class Good(models.Model):
    name = models.CharField(max_length=50)
    club = models.ForeignKey("social.Club", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def price_object(self):
        return Price.objects.filter(good=self).order_by("-date")[0]

    def price(self):
        return self.price_object().price

    def price_at_date(self, date):
        return (
            Price.objects.filter(good=self, date__lte=date).order_by("-date")[0].price
        )


class Transaction(models.Model):
    good = models.ForeignKey("Good", on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()
    student = models.ForeignKey("social.Student", on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField()

    def __str__(self):
        string_to_return = self.good.name + " : "
        if self.student is not None:
            string_to_return += self.student.user.username
        return string_to_return

    def balance_change_for_student(self):
        return -(self.quantity * self.good.price_at_date(self.date))

    def balance_change_for_club(self):
        return self.quantity * self.good.price_at_date(self.date)


class TradeAdmin(models.Model):
    student = models.ForeignKey("social.Student", on_delete=models.CASCADE)
    club = models.ForeignKey("social.Club", on_delete=models.CASCADE)
    manage_admins = models.BooleanField(default=False)
    manage_goods = models.BooleanField(default=False)
    manage_transactions = models.BooleanField(default=False)
    manage_credits = models.BooleanField(default=False)

    class Meta:
        unique_together = ("student", "club")

    def __str__(self):
        return "TradeAdmin: {} for {}".format(
            self.student.user.username, self.club.name
        )

back/pochtron/forms.py
from django import forms

from .models import Alcohol


class EditAlcohol(forms.ModelForm):
    class Meta:
        model = Alcohol
        fields = (
            "name",
            "club",
            "degree",
            "volume",
        )
        widgets = {
            "name": forms.TextInput(attrs={"class": "profil-input"}),
            "degree": forms.TextInput(attrs={"class": "profil-input"}),
            "volume": forms.TextInput(attrs={"class": "profil-input"}),
        }

    def __init__(self, *args, **kwargs):
        super(EditAlcohol, self).__init__(*args, **kwargs)

back/pochtron/templates/pochtron/admin.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Pochtron" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-main">
            {% if admin.manage_goods %}
                <a href="{% url 'pochtron:conso_create' %}" style="text-decoration: none"><button class="button blue-button">Créer une consommation</button></a>
            {% else %}
                <button class="button disabled-button">Créer une consommation</button>
            {% endif %}
            {% if admin.manage_transactions %}
                <a href="{% url 'pochtron:shop' %}" style="text-decoration: none"><button class="button blue-button">Foyer</button></a>
            {% else %}
                <button class="button disabled-button">Foyer</button>
            {% endif %}
            {% if admin.manage_credits %}
                <a href="{% url 'pochtron:manage_accounts' %}" style="text-decoration: none"><button class="button blue-button">Comptes</button></a>
            {% else %}
                <button class="button disabled-button">Comptes</button>
            {% endif %}
            {% if admin.manage_admins %}
                <a href="{% url 'pochtron:manage_admins' %}"><button class="button blue-button">Gestion des admins de Pochtron</button></a>
            {% endif %}
            <h1>Toutes les consommations :</h1>
            <table class="table">
                <thead>
                    <tr>
                        <td>Consommation</td>
                        <td>Volume (mL)</td>
                        <td>Degré (%)</td>
                        <td>Prix</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    {% for conso in consommations %}
                        <tr style="vertical-align: middle">
                            <td>{{conso.name}}</td>
                            <td>{{conso.volume}}</td>
                            <td>{{conso.degree}}</td>
                            <td>{{conso.price_euro|floatformat:2}} €</td>
                            <td>
                                {% if admin.manage_goods %}
                                    <a href="{% url 'pochtron:conso_edit' conso.id %}" style="text-decoration: none"><button class="button blue-button">Modifier</button></a>
                                {% else %}
                                    <button class="button disabled-button">Modifier</button>
                                {% endif %}
                            </td>
                        </tr>
                    {% empty %}
                        <th colspan="5" style="text-align: center">Aucune consommation.</th>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
</body>
</html>

back/pochtron/templates/pochtron/create_consos.html
{% load static %}
<!--Header-->
{%if create%}
    {% include "header.html" with title="Créer une consommation" %}
{%else%}
    {% include "header.html" with title="Modifier une consommation" %}
{%endif%}
<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-main">
            {%if create%}
                <h3 class="page-title">Créer une nouvelle consommation</h3>
            {%else%}
                <h3 class="page-title">Modifier une consommation</h3>
            {%endif%}
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="news-card">
                    <div class="news-card-content">
                        {{EditAlcohol.name.errors}}
                        Nom :<br>
                        {{EditAlcohol.name}}<br>
                        {{EditAlcohol.volume.errors}}
                        Volume (mL) :<br>
                        {{EditAlcohol.volume}}<br>
                        {{EditAlcohol.degree.errors}}
                        Taux d'alcool (%) :<br>
                        {{EditAlcohol.degree}}<br>
                        {{EditPrice.price.errors}}
                        Prix :<br>
                        {{EditPrice.price}}<br>
                        <script>
                            $(function () {
                                $("#id_price").mask("000,00 \€", {
                                    placeholder: "000,00 €",
                                    reverse: true
                                });
                            });
                        </script>
                    </div>
                    <div class="news-card-actions">
                        <div class="news-card-popularity">
                            <a href="{% url 'pochtron:admin' %}"><span class="button red-button">Annuler</span></a>
                            <input class="button green-button" type="submit" name= "Valider" value="Valider">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
</body>
</html>

back/pochtron/templates/pochtron/home.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Pochtron" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">

        <!--Content
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
            </div>
        </div>
        -->

        <div class="content-main">
            {% if admin %}
                <a href="{% url 'pochtron:admin' %}" style="text-decoration: none"><button class="button blue-button">Admin</button></a>
            {% endif %}


            <h2 class="section-title">Mon solde actuel : {{ user_balance }} €</h2>

            <!--Row-->
            <div class="row">

                <!--Column-->
                <div class="col">
                    <h4 class="page-subtitle-3">Mes transactions</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <td>Consommation</td>
                                <td>Quantité</td>
                                <td>Débit / Crédit</td>
                                <td>Date</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for t in transactions %}
                                <tr style="vertical-align: middle">
                                    <td>{{t.product}}</td>
                                    <td>{{t.quantity}}</td>
                                    <td>{{t.price}} €</td>
                                    <td>{{t.date}}</td>
                                </tr>
                            {% empty %}
                                <th colspan="4" style="text-align: center">Aucune transactions</th>
                            {% endfor %}
                        </tbody>
                    </table>
                </div><!--End of Column-->

                {% comment %}
                <!--Column-->
                <div class="col">
                    <h4 class="page-subtitle-3">Évolution de mon solde</h4>
                    <div id="graph">
                        <!--The graph will be rendered here with React-->
                    </div>
                </div><!--End of Column-->
                {% endcomment %}

            </div><!--End of Row-->
        </div><!--End of Main Content-->

    </div><!--End Of Content-->


    <!--Scripts-->
    <script src="{% url 'reverse_js' %}" type="text/javascript"></script> <!--Put this script before any react script to be able to reverse django urls in react-->
    {% comment %}
    <script>
        window.react_mount = document.getElementById("graph");
    </script>
    <script src="{% static 'react/pochtron_overview.bundle.js' %}"></script>
    {% endcomment %}
</body>
</html>

back/pochtron/templates/pochtron/manage_accounts.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Comptes" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
                <div class="col" align="right">
                    <a href="{% url 'pochtron:admin' %}"><button class="button blue-button">Retourner sur la page d'administration</button></a>
                </div>
            </div>
        </div>
        <div class="content-main">
            <div id="manager">
                <!--Manager is render here with React-->
            </div>
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
    <script src="{% url 'reverse_js' %}" type="text/javascript"></script> <!--Put this script before any react script to be able to reverse django urls in react-->
    <script>
        window.react_mount = document.getElementById("manager");
    </script>
    <script src="{% static 'react/pochtron_manage_accounts.bundle.js' %}"></script>
</body>
</html>

back/pochtron/templates/pochtron/manage_admins.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Pochtron" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
                <div class="col" align="right">
                    <a href="{% url 'pochtron:admin' %}"><button class="button blue-button">Retourner sur la page d'administration</button></a>
                </div>
            </div>
        </div>
        <div class="content-main">

            <!--Row-->
            <div class="row">
                <!--Col-->
                <div class="col">
                    <h1>Admins de Pochtron :</h1>
                </div><!--End of Col-->

                <!--Col-->
                <div class="col" align="right">
                    <a href={% url 'pochtron:admin_create' %}><button class="button blue-button">Ajouter un nouvel admin</button></a>
                </div><!--End of Col-->

            </div><!--End of Row-->

            <table class="table">
                <thead>
                    <tr>
                        <td>Élèves</td>
                        <td>Peut créer/modifier les consommations</td>
                        <td>Peut ajouter des transactions</td>
                        <td>Peut créditer les comptes</td>
                        <td>Peut gérer les administrateurs</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    {% for admin in admins %}
                        <tr style="vertical-align: middle">
                            <td>{{admin.student.user.first_name}} {{admin.student.user.last_name}}</td>
                            <td>{{ admin.manage_goods|yesno }}</td>
                            <td>{{ admin.manage_transactions|yesno }}</td>
                            <td>{{ admin.manage_credits|yesno }}</td>
                            <td>{{ admin.manage_admins|yesno }}</td>
                            <td>
                                <a href={% url 'pochtron:admin_edit' admin.pk %} ><button class="button blue-button">Modifier</button></a>
                            </td>
                        </tr>
                    {% empty %}
                        <!--Normally this cannot happend-->
                        <th colspan="5" style="text-align: center">Aucun administrateurs</th>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
</body>
</html>

back/pochtron/templates/pochtron/shop.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Pochtron" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
                <div class="col" align="right">
                    <a href="{% url 'pochtron:admin' %}"><button class="button blue-button">Retourner sur la page d'administration</button></a>
                </div>
            </div>
        </div>
        <div class="content-main">
            <div id="shop">
                <!--The shop is rendered here with React-->
            </div>
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
    <script src="{% url 'reverse_js' %}" type="text/javascript"></script> <!--Put this script before any react script to be able to reverse django urls in react-->
    <script>
        window.react_mount = document.getElementById("shop");
    </script>
    <script src="{% static 'react/pochtron_shop.bundle.js' %}"></script>
</body>
</html>

back/pochtron/templates/pochtron/user_stats.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Pochtron" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="pochtron" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col" align="right">
                    <a href="{% url 'pochtron:admin' %}"><button class="button blue-button">Retourner sur l'accueil de Pochtron</button></a>
                </div>
            </div>
        </div>
        <div class="content-main">
            <div id="charts" style="height=100%; width=100%">
                <!--Charts are rendered here using React-->
            </div>
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
    <script src="{% url 'reverse_js' %}" type="text/javascript"></script> <!--Put this script before any react script to be able to reverse django urls in react-->
    <script>
        window.react_mount = document.getElementById("charts");
    </script>
    <script src="{% static 'react/PochtronUserStats.bundle.js' %}"></script>
</body>
</html>