back/courses/urls.py
from django.urls import path

from news.views import post_create, post_edit

from . import views

app_name = "courses"

urlpatterns = [
    path("courses/", views.index_courses, name="courses_index"),
    path("course/<int:course_id>/details", views.view_course, name="course_detail"),
    path("update_timeslots/", views.update_timeslots, name="update_timeslots"),
    path("group/<int:group_id>/<str:action>", views.join_group, name="join_group"),
    path("add_course/", views.add, name="add_course"),
    path(
        "course/<int:course_id>/post/create",
        post_create,
        name="course_post_create",
    ),
    path(
        "course/<int:course_id>/post/<int:post_id>/edit",
        post_edit,
        name="course_post_edit",
    ),
]

back/news/urls.py
from django.urls import path

from . import views

app_name = "news"

urlpatterns = [
    path("post/", views.posts, name="posts"),
    path("event/", views.events, name="events"),
    path("event/<int:event_id>/detail", views.event_detail, name="event_detail"),
    path("event/<int:event_id>/edit", views.event_edit, name="event_edit"),
    path("event/create", views.event_create, name="event_create"),
    path(
        "event/<int:event_id>/<str:action>",
        views.event_participate,
        name="event_participate",
    ),
    path("post/<int:post_id>/edit", views.post_edit, name="post_edit"),
    path("post/create", views.post_create, name="post_create"),
    path(
        "post/create/<int:event_id>", views.post_create, name="post_create_with_origin"
    ),
    path("post/<int:post_id>/<str:action>", views.post_like, name="post_like"),
    path("comment/add/<int:post_id>/", views.comment_post, name="comment_post"),
    path(
        "comment/delete/<int:comment_id>/",
        views.delete_comment,
        name="comment_delete",
    ),
    path("shotgun/", views.shotguns, name="shotguns"),
    path("shotgun/<int:shotgun_id>/", views.shotgun_detail, name="shotgun_detail"),
    path(
        "shotgun/<int:shotgun_id>/participate/",
        views.shotgun_participate,
        name="shotgun_participate",
    ),
    path("shotgun/new/", views.new_shotgun, name="new_shotgun"),
    path(
        "shotgun/<int:shotgun_id>/delete/",
        views.delete_shotgun,
        name="delete_shotgun",
    ),
    path(
        "shotgun/<int:shotgun_id>/edit/",
        views.edit_shotgun,
        name="edit_shotgun",
    ),
    path("shotgun/admin/", views.shotguns_admin, name="shotguns_admin"),
    path(
        "shotgun/<int:shotgun_id>/admin/",
        views.shotguns_admin_detail,
        name="shotguns_admin_detail",
    ),
    path(
        "shotgun/admin/fail/<int:participation_id>",
        views.fail_participation,
        name="fail_participation",
    ),
    path(
        "shotgun/admin/unfail/<int:participation_id>",
        views.unfail_participation,
        name="unfail_participation",
    ),
    path(
        "shotgun/<int:shotgun_id>/admin/publish_shotgun_results/",
        views.publish_shotgun_results,
        name="publish_shotgun_results",
    ),
    path(
        "markdown",
        views.markdown,
        name="markdown",
    ),
    path("bookmarks/", views.bookmarks, name="bookmarks"),
]

back/upont/urls.py
import django_cas_ng.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django_reverse_js.views import urls_js
from rest_framework import routers

from courses.views import (
    CourseViewSet,
    GroupViewSet,
    ListCourseDepartments,
    ResourceViewSet,
    TimeslotViewSet,
)
from news.views import (
    DeleteCommentView,
    EventViewSet,
    PartnershipViewSet,
    PostCommentView,
    PostCreateView,
    PostCreateViewV2,
    ShotgunCreateView,
    PostDeleteView,
    PostEditView,
    PostReactionView,
    PostViewSet,
    SearchPost,
    ShotgunParticipateView,
    ShotgunView,
)
from pochtron.views import (
    CagnotteURL,
    PochtronBalance,
    PochtronId,
    PochtronTransactions,
    SearchAlcohol,
)

# Replace MediatekViewSet with LocalViewSet
from services.views import (
    BikesViewSet,
    LocalViewSet,
    OrderViewSet,
    RequestFormViewSet,
    ReservationBikeViewSet,
    ReservationMusicRoomViewSet,
    VracViewSet,
)
from social.views import (
    ClubsViewSet,
    CurrentStudentView,
    NotificationTokenView,
    OneClubView,
    OneStudentView,
    ProfilePicUpdate,
    SearchClub,
    SearchRole,
    SearchStudent,
    StudentCanPublishAs,
    StudentMembershipView,
    StudentProfileEdit,
    StudentViewSet,
    validate_student,
)
from the_calendar.views import CalendarData
from trade.views import LastTransactions, add_transaction, credit_account

from . import views

# ---- MAIN URLS ----#

urlpatterns = [
    path("social/", include("social.urls")),
    path("news/", include("news.urls")),
    path("pochtron/", include("pochtron.urls")),
    path("courses/", include("courses.urls")),
    path("the_calendar/", include("the_calendar.urls")),
    path("admin/", admin.site.urls),
    path("tellme/", include("tellme.urls"), name="tellme"),
    path("add_promo/", views.add, name="add_promo"),
    path(
        "login/",
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name="login",
    ),  # forces redirection of already authenticated users
    path("", include("django.contrib.auth.urls")),
    path("", views.root_redirect),
    path("internal/auth-check/", views.auth_check, name="internal_auth_check"),
    path("cas/login", django_cas_ng.views.LoginView.as_view(), name="cas_ng_login"),
    path("cas/logout", django_cas_ng.views.LogoutView.as_view(), name="cas_ng_logout"),
    path("page_not_created/", views.page_not_created, name="page_not_created"),
    path("privacy", views.privacy, name="privacy"),
    path("contact", views.contact, name="contact"),
]

if settings.DEBUG:  # in debug anyone can access any image
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns.append(path("media/<path:path>", views.media))

# ---- API URLS ----#

router = routers.DefaultRouter()
router.register(
    r"admin-status", views.AdminStatusViewSet, basename="check-admin-status"
)
router.register(r"students", StudentViewSet)
router.register(r"posts", PostViewSet, basename="post")
router.register(r"events", EventViewSet, basename="event")
router.register(r"courses", CourseViewSet, basename="course")
router.register(r"groups", GroupViewSet, basename="group")
router.register(r"timeslots", TimeslotViewSet, basename="timeslot")
router.register(r"resources", ResourceViewSet, basename="resource")
router.register(r"clubs", ClubsViewSet)
router.register(r"services/bikes", BikesViewSet, basename="bikes")
router.register(r"services/orders", OrderViewSet, basename="order")
router.register(r"services/vrac", VracViewSet, basename="vrac")
router.register(r"services/requests", RequestFormViewSet, basename="requests")
router.register(
    r"services/reservations", ReservationBikeViewSet, basename="reservations"
)
router.register(
    r"services/musicroom", ReservationMusicRoomViewSet, basename="musicroom"
)
router.register(r"services/locals", LocalViewSet, basename="local")

router.register(r"partnerships", PartnershipViewSet, basename="partnership")

urlpatterns += [
    path(
        "reverse.js", urls_js, name="reverse_js"
    ),  # for reversing django urls in JavaScript
    path("api/", include(router.urls)),
    path("api/current/", CurrentStudentView.as_view(), name="current_student"),
    path(
        "api/transactions/last/", LastTransactions.as_view(), name="last_transactions"
    ),
    path("api/forms/publish/", StudentCanPublishAs.as_view(), name="publish_comment"),
    path("api/forms/transactions/add/", add_transaction, name="add_transaction"),
    path("api/forms/transactions/credit/", credit_account, name="credit_account"),
    path("api/search/roles/", SearchRole.as_view(), name="search_roles"),
    path("api/search/students/", SearchStudent.as_view(), name="search_students"),
    path("api/search/clubs/", SearchClub.as_view(), name="search_clubs"),
    path("api/search/alcohols/", SearchAlcohol.as_view(), name="search_alcohols"),
    path("api/search/posts/", SearchPost.as_view(), name="search_posts"),
    path("api/id/pochtron/", PochtronId.as_view(), name="pochtron_id"),
    path(
        "api/course_departments/",
        ListCourseDepartments.as_view(),
        name="course_department_list",
    ),
    path("api/calendar_data/", CalendarData.as_view(), name="calendar_data"),
    path("api/get_token/", views.get_token, name="get_token"),
    path("api/get_sso_token/", views.get_sso_token, name="get_sso_token"),
    path("api/shotguns/", ShotgunView.as_view(), name="shotgun"),
    path(
        "api/shotgun/participate/",
        ShotgunParticipateView.as_view(),
        name="shotgun_participate",
    ),
    path(
        "api/notification_token/", NotificationTokenView.as_view(), name="student_token"
    ),
    path("api/post_reaction/", PostReactionView.as_view(), name="post_reaction"),
    path(
        "api/news/post/delete/", PostDeleteView.as_view(), name="api_news_post_delete"
    ),
    path(
        "api/news/comment/delete/",
        DeleteCommentView.as_view(),
        name="api_news_comment_delete",
    ),
    path("api/comment_post/", PostCommentView.as_view(), name="post_comment"),
    path("api/create_post/", PostCreateView.as_view(), name="post_creation"),
    path("api/create_post/v2/", PostCreateViewV2.as_view(), name="post_creation_v2"),
    path("api/create_shotgun/", ShotgunCreateView.as_view(), name="create_shotgun"),
    path("api/edit_post/", PostEditView.as_view(), name="post_edit"),
    path("api/student/", OneStudentView.as_view(), name="student"),
    path("api/membership/", StudentMembershipView.as_view(), name="membership"),
    path("api/club/", OneClubView.as_view(), name="club"),
    path("api/media/<path:path>", views.get_media_path, name="get_media_path"),
    path("api/pochtron/balance/", PochtronBalance.as_view(), name="pochtron_balance"),
    path(
        "api/pochtron/transactions/",
        PochtronTransactions.as_view(),
        name="pochtron_transactions",
    ),
    path("api/pochtron/cagnotte_url/", CagnotteURL.as_view(), name="cagnotte_url"),
    path("api/test/", ProfilePicUpdate.as_view(), name="test"),
    path("api/edit_profile/", StudentProfileEdit.as_view(), name="edit_profile"),
    path("api/validate-student/", validate_student, name="validate_student"),
]

back/courses/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from news.models import Post
from social.models import Student


class Teacher(models.Model):
    name = models.CharField(max_length=100, default="Professeur anonyme")

    def __str__(self):
        return self.name


class CourseDepartment(models.TextChoices):
    IMI = "IMI", _("Ingénierie mathématique et informatique")
    GCC = "GCC", _("Génie civil et construction")
    GMM = "GMM", _("Génie mécanique et matériaux")
    SEGF = "SEGF", _("Sciences économiques, gestion, finance")
    VET = "VET", _("Ville, environnement, transport")
    GI = "GI", _("Génie industriel")
    A1 = "1A", _("Première année")
    DE = "DE", _("Direction de l'enseignement")
    DLC = "DLC", _("Département langues et culture")
    SHS = "SHS", _("Sciences humaines et sociales")
    PAPDD = "PAPDD", _("Politique et action publique pour le développement durable")
    DS = "D.SCHOOL", _("d.school")
    AHE = "AHE", _("Autres hors école")


class Course(models.Model):
    name = models.CharField(max_length=100, default="Cours sans nom")
    acronym = models.CharField(max_length=100, default="ABC")
    department = models.CharField(
        max_length=8, choices=CourseDepartment.choices, default=CourseDepartment.AHE
    )
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)

    description = models.TextField()
    old_courses = models.ManyToManyField(
        "self",
        through="CourseUpdate",
        symmetrical=False,
        related_name="new_courses",
        blank=True,
    )
    posts = models.ManyToManyField(
        Post,
        related_name="course",
        blank=True,
    )

    def __str__(self):
        return self.name


class CourseUpdate(models.Model):
    date = models.DateTimeField()
    old_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="old")
    new_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="new")

    def __str__(self):
        return self.old_course.name + " : " + self.new_course.name


class Group(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="groups")
    teacher = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, related_name="groups"
    )
    number = models.IntegerField(blank=True, null=True)
    students = models.ManyToManyField(
        Student,
        through="Enrolment",
        related_name="course",
        blank=True,
    )

    def __str__(self):
        if self.number is None:
            return "{} : {}".format(self.course.name, self.teacher.name)
        else:
            return "{} ({}) : {}".format(
                self.course.name, self.number, self.teacher.name
            )


class Enrolment(models.Model):
    is_old = models.BooleanField(default=False)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    def __str__(self):
        return self.group.course.name + " : " + self.student.user.username


class Timeslot(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    course_groups = models.ManyToManyField(Group, related_name="timeslot", blank=True)
    place = models.CharField(max_length=50, blank=True)

    def get_course_name(self):
        """
        Return the name of the corresponding course
        Return None if it is attached to no course
        """
        if self.course_groups.exists():
            course_name = self.course_groups.first().course.name
        else:
            course_name = None

        return course_name


class Resource(models.Model):
    name = models.CharField(max_length=50, default="Ressource")
    author = models.ForeignKey(
        "social.Student", verbose_name="author", on_delete=models.SET_NULL, null=True
    )
    date = models.DateTimeField()
    file = models.FileField("Fichier", upload_to="ressources", null=True, blank=True)
    post = models.ForeignKey(
        "news.Post",
        verbose_name="post",
        on_delete=models.CASCADE,
        null=True,
        related_name="resource",
    )

back/courses/templates/courses/add_course.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Ajout d'un cours" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="admin" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <div class="col">
                    <div class="search-input-group">
                        <input type="text" class="search-input" placeholder="Rechercher">
                        <button class="button search-button"><i class="fas fa-search "></i></button>
                    </div>
                </div>
                <!--<div class="col" style="text-align: end;">
                        <button class="button"><i class="fas fa-bell"></i></button>
                        <button class="button"><i class="fas fa-bell"></i></button>
                    </div>-->
            </div>
        </div>
        <div class="content-main">
            <p> Les informations doivent être dans l'ordre suivant : {{order}}.</p>
            <p>Utiliser le format CSV uniquement, avec encodage UTF-8, délimité avec ";".</p>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" id="file1" name="file">
                <button type="submit">Uploader</button>
            </form><br>
            {% if type_error %}
                <strong>Erreur: le fichier doit être au format .csv .</strong><br><br>
            {% endif %}
            {% if no_file %}
                <strong>Erreur: Aucun fichier n'a été uploadé.</strong><br><br>
            {% endif %}
            {% if list_courses_not_added %}
                <strong>Les cours n'ont pas été ajoutés.</strong><br><br>
            {% endif %}
            {% if list_courses_added %}
                <strong>Les cours ont étés ajoutés.</strong><br><br>
            {% endif %}
            {% if courses_not_added %}
                <p>Les étudiants suivants n'ont pas pu être ajoutés :</p>
                {% for course in courses_not_added %}
                    <li>{{course}}</li>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
    <script src="{% static 'js/sidenav.js' %}"></script>
</body>
</html>

back/courses/templates/courses/add_courses.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Ajout d'un cours" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="admin" %}

    <!--Content-->
    <div class="content">
        <div class="content-header">
            <div class="row justify-content-between w-100">
                <!--<div class="col" style="text-align: end;">
                        <button class="button"><i class="fas fa-bell"></i></button>
                        <button class="button"><i class="fas fa-bell"></i></button>
                    </div>-->
            </div>
        </div>
        <div class="content-main">
            <p> Les informations doivent être dans l'ordre suivant : {{order}}.</p>
            <p>Utiliser le format CSV uniquement, avec encodage UTF-8, délimité avec ";".</p>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" id="file1" name="file">
                <button type="submit">Uploader</button>
            </form><br>
            {% if type_error %}
                <strong>Erreur: le fichier doit être au format .csv .</strong><br><br>
            {% endif %}
            {% if no_file %}
                <strong>Erreur: Aucun fichier n'a été uploadé.</strong><br><br>
            {% endif %}
            {% if list_courses_not_added %}
                <strong>Les cours n'ont pas été ajoutés.</strong><br><br>
            {% endif %}
            {% if list_courses_added %}
                <strong>Les cours ont étés ajoutés.</strong><br><br>
            {% endif %}
            {% if courses_not_added %}
                <p>Les cours suivants n'ont pas pu être ajoutés :</p>
                {% for course in courses_not_added %}
                    <li>{{course}}</li>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <!--EndContent-->

    <!--Scripts-->
    <script src="{% static 'js/sidenav.js' %}"></script>
</body>
</html>

back/courses/templates/courses/index_courses.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Cours" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="courses" %}

    <!--Content-->
    <div class="content">

        <!--Header Content-->

        <!--Main Content-->
        <div class="content-main">

            <h3 class="page-title">
                Cours
            </h3>
            <div id="courses">
                <!--Courses list is rendered here with React-->
            </div>
        </div><!--End of Main Content-->

    </div><!--End of Content-->

    <!--Scripts-->
    <script src="{% url 'reverse_js' %}" type="text/javascript"></script> <!--Put this script before any react script to be able to reverse django urls in react-->
    <script>
        window.react_mount = document.getElementById("courses");
    </script>
    <script src="{% static 'react/index_courses.bundle.js' %}"></script>
</body><!--End of Body-->
</html><!--End of Document-->

back/courses/templates/courses/update_timeslots.html
{% load static %}
<!--Header-->
{% include "header.html" with title="Mise à jour manuel des créneaux de cours" %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="admin" %}

    <!--Content-->
    <div class="content">

        <!--Header Content-->

        <!--Main Content-->
        <div class="content-main">

            <h3 class="page-title">
                Mise à jours des crénaux de cours
            </h3>

            {% if bad_input %}
                <p class="text-red">Format de date incorrect. Utiliser le format "jour/mois/année" </p>
            {% endif %}
            {% if updated %}
                <p class="text-green">Crénaux mis à jour pour la date {{date}}</p>
            {% endif %}
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" id="date" name="date">
                <script>
                    $( function() {
                        var $input = jQuery.noConflict();
                        $input( "#date" ).datetimepicker({
                            format: "d/m/Y"
                        });
                    } );
                </script>
                <button type="submit">Mettre à jour</button>
            </form><br>
        </div><!--End of Main Content-->

    </div><!--End of Content-->
</body><!--End of Body-->
</html><!--End of Document-->

back/courses/templates/courses/view_course.html
{% load static %}
<!--Markdownify-->
{% load markdownify %}
<!--Header-->
{% if course.acronym %}{% include "header.html" with title=course.acronym|add:"-"|add:course.name %}{% else %}{% include "header.html" with title=course.name %}{% endif %}

<!--Body-->
<body>
    <!--Feedback Button-->
    {% include "feedback.html" %}

    <!--Sidenav-->
    {% include "sidenav.html" with active_link="courses" %}

    <!--Content-->
    <div class="content">

        <!--Main Content-->
        <div class="content-main">

            <a href={% url 'courses:courses_index' %} style="margin-left: auto;"><button class="button green-button">Retour à l'index</button></a>

            <!--Course Box-->
            <div class="course-box">
                <!--Row-->
                <div class="row">
                    <!--Column-->
                    <div class="col-12">
                        <div class="course-title">
                            <h4> {{course.name}} - {{course.acronym}} </h4>
                            <h5 class="text-bold mt-1">{{course.teacher}} - {{course.department}}</h5>
                        </div>
                    </div><!--End of Column-->


                    {%if course.new_courses.all%}
                        <!--Column-->
                        <div class="col-12">
                            <h6 class="text-warning">Ce cours n'existe plus, voici le(s) cours ayant vocation à le remplacer :</h5>
                            {%for new_course in course.new_courses.all%}
                                <a href={% url 'courses:course_detail' course_id=new_course.id %}> {{new_course.name}} - ({{new_course.acronym}})</a>
                            {%endfor%}
                        </div><!--End of Column-->
                    {%endif%}

                    <!--Column-->
                    <div class="col-12">
                        {%if course.groups.all|length_is:1%}
                            {%for group in course.groups.all%}
                                {%if group in student.course.all%}
                                    <a href={%url 'courses:join_group' group_id=group.id action="Leave_course"%}>
                                        <button class="button red-button"> Quitter le cours</button>
                                    </a>
                                {%else%}
                                    <a href={%url 'courses:join_group' group_id=group.id action="Join_course"%}>
                                        <button class="button blue-button"> Rejoindre le cours</button>
                                    </a>
                                {%endif%}
                            {%endfor%}
                        {%elif course.groups.all%}
                            <div class="group-box">
                                <h5 class="text-bold mt-2"> Groupes : </h5>
                                {%for group in course.groups.all%}
                                    {%if group.number is not None%}
                                        <div class="col-lg-12">
                                            Groupe {{group.number}} : {{group.teacher}}
                                            {%if group in student.course.all%}
                                                <a href={%url 'courses:join_group' group_id=group.id action="Leave_group"%}>
                                                    <button class="button red-button"> Quitter </button>
                                                </a>
                                            {%else%}
                                                <a href={%url 'courses:join_group' group_id=group.id action="Join_group"%}>
                                                    <button class="button blue-button"> Rejoindre </button>
                                                </a>
                                            {%endif%}
                                        </div>
                                    {%endif%}
                                {%endfor%}
                            </div> <!--End of Column-->
                        {%endif%}

                    </div><!--End of Column-->

                    <!--Column-->
                    <div class="col-12">
                        <h5 class="text-bold mt-2">Description du cours :</h5>
                        <p class="text-thin text-justified mt-2" style="font-size: medium;">{{course.description|markdownify}}</p>
                    </div><!--End of Column-->

                </div><!--End of Course Box-->

            </div><!--End of Row-->

        </div><!--End of Main Content-->

        <h4 class="page-title">Posts</h4>
        <div class="centered-div mt-2">
            <a href="{% url 'courses:course_post_create' course_id=course.id %}">
                <button class="button blue-button "><i class="fas fa-plus-circle fa-2x logo-button"></i>Ajouter un post</button>
            </a>
        </div>
        <div id="posts">
            <!--Posts are rendered here by react-->
        </div>

    </div><!--End of Content-->

    <!--Scripts-->
    <script src="{% url 'reverse_js' %}" type="text/javascript"></script> <!--Put this script before any react script to be able to reverse django urls in react-->
    <script>
        const courseId = {{course.pk}};
        window.react_mount = document.getElementById("posts");
    </script>
    <script src="{% static 'react/course_posts.bundle.js' %}"></script>

</body><!--End of Body-->

</html><!--End of Document-->